### ISSUE TITLE
关于下拉上拉刷新与正常滑动的bug

### ISSUE THREAD

**Issue by scofieldpeng** [ximan/dropload#1]
试了下，发现在正常的列表页面中滑动也会造成“下拉刷新/下拉加载”的问题，还没有看源码，好像没有判断是否在底部/顶部？

**Comment by ximan** [comment]
你好，感谢关注这个项目。
你说的滑动也会触发，可否提供一下测试手机型号和浏览器？我iPhone测试是正常的。

**Comment by scofieldpeng** [comment]
在chrome（Version 41.0.2272.76 (64-bit)），小米2s，某国产安卓以及5s上的微信内置浏览器测试皆有此问题：）

**Comment by ximan** [comment]
Chrome（41.0.2272.104 (64-bit)），iPhone 5s微信内置，都没发现你说的问题。
是不是我操作习惯跟你的不一样？
可否详细讲一下你的操作方式？
我非常关注这个问题，因为我们已经用在正式项目中了。还希望你能抽一点时间来说明一下，非常感谢你哈！

**Comment by changexbc** [comment]
0.3.0版本中如果上拉再迅速下拉，会导致插件不可用，再次上拉无法加载。

**Comment by ximan** [comment]
@changexbc 谢谢反馈。
可否说明一下设备和浏览器？
我在iPhone 5s的safari上，上拉loading的时候再下拉，是不会有影响的。

**Comment by changexbc** [comment]
@ximan 你的博客上的demo用的是0.2.0是没有问题的 但是0.3.0在ios8.3下有问题 safari微信webview都有这个问题

**Comment by ximan** [comment]
@changexbc 我这个github项目首页（https://github.com/ximan/dropload/ ）有个二维码，你试试，是0.3.0的。我手机还是8.2，我升级一下。

**Comment by changexbc** [comment]
@ximan 试过了，同样有问题，我发现上拉并且快速下拉多次之后me.loading的值为true...我发现只要上滑不松手再下滑到底就会出现这个问题

**Comment by ximan** [comment]
@changexbc 感谢，我依旧测不出来问题。。。你要是有兴趣欢迎修改一下提交吧

**Comment by changexbc** [comment]
@ximan 感谢你耐心的回复，我提交了一个暂时的解决方法，不知道为啥你测不出，我在chrome模拟界面下都有这个问题，发现在ios下scroll事件在touchend之后才会触发，这个机制使得这个插件的体验不是很好，我还是打算试下用全部使用touch事件来模拟滚动条，再次感谢

**Comment by ximan** [comment]
@changexbc 感谢你贡献的代码，近期工作比较忙，我还是会抽空继续优化的。scroll确实体验不好，一直不敢下定决心像淘宝首页那样，直接抛弃scroll啊。
有好的解决方案记得分享一下，谢谢

**Comment by Falld0wn18** [comment]
5S IOS 8.4下的浏览器拖动页面好像会跳动。。。。是我的错觉还是。。

**Comment by ximan** [comment]
@Falld0wn18 一直都有，还不知道怎么解决>_<

**Comment by Falld0wn18** [comment]
@ximan  (┬＿┬) 我找了一天的插件，愣是没找到解决方案。

**Comment by zsxsoft** [comment]
在Chrome 46.0.2490.6（Windows）下模拟也会出现这种现象，于是现在加了一段Hack代码……
jQuery v2.1.1

**Comment by tao1587** [comment]
更改了你的 才ok
totalheight = parseFloat($(window).height()) + parseFloat($(window).scrollTop());
    if($(document).height() <= totalheight){

**Comment by ximan** [comment]
@GoToBoy 感谢关注这个项目，请问你这一句是加在哪里，第几行？

**Comment by tao1587** [comment]
@ximan 135行 判断是否下拉；
没看到你代码里面有判断是否滚动到最底部，然后再加载更多的代码，你是漏掉了？

**Comment by ximan** [comment]
@GoToBoy 有写啊。
0.3.0在这里：https://github.com/ximan/dropload/blob/0.3.0/dist/dropload.js#L118
0.4.0在这里：https://github.com/ximan/dropload/blob/gh-pages/dist/dropload.js#L135

**Comment by tao1587** [comment]
@ximan 我跟你的DOM结构一样，但是css样式不一样，判断出的childrenheight 一直为0；

**Comment by ximan** [comment]
@GoToBoy 之前因为我结构比较特殊，所以很多人用起来都有问题。0.4.0更新到最普通的结构，你再试试看。
欢迎多多反馈，谢谢

**Comment by ximan** [comment]
上拉跳动已经在0.5.0去掉，不会再跳了。

**Comment by changexbc** [comment]
👍
目前在微信等webview下scrollTop的值只有在松开手指的时候更新的问题除了模拟滚动的方法是否有解决方案？不然需要两次滚动才能触发下拉刷新体验并不太好

**Comment by ximan** [comment]
@changexbc 不好处理。在我做这次更新的时候，曾尝试下拉刷新一次性执行，结果就是网页继续抖动，原因依旧是scroll和touch同时作用而抖动。如果你项目特殊，非要这样做，建议换思路，例如全部模拟scroll，把系统的scroll禁掉。

**Comment by changexbc** [comment]
@ximan 3q
