### ISSUE TITLE
请问lock('down')之后，再次进行up,那么这个时候lock('down')还是锁定的，为什么不能在up操作的时候去解锁unlock()呢？

### ISSUE THREAD

**Issue by Hopingocean** [ximan/dropload#102]
请问lock('down')之后，再次进行up,那么这个时候lock('down')还是锁定的，为什么不能在up操作的时候去解锁unlock()呢？如果在up里使用unlock(),并且使用resetload(),加载动画也不会隐藏，会一直显示正在加载。

（目前我是在lock('down')之后，resetload()之前使用解锁unlock(),但是这样我又何必去lock()呢？）

还是说我使用的方法有问题。谢谢

**Comment by ximan** [comment]
你好，你的问题是，锁了down，不能up刷新了，对吗？

**Comment by Hopingocean** [comment]
业务逻辑是：如果先down，然后lock('down'), 此时再去up刷新，然后再去down,但是down还处于锁定状态，不能down刷新了。（逻辑上应该是在up刷新的时候解锁down，但是up刷新的时候使用unlock()会导致up刷新的状态框‘正在加载’一直显示，没有被隐藏）

**Comment by Hopingocean** [comment]
你好，今天突然想到了一点，去尝试了一下在up之后先resetload，然后unlock，这样就可以正常运行了，不过不知道为什么？
