### ISSUE TITLE
向下加载最多加载多少呢？

### ISSUE THREAD

**Issue by yinxr** [ximan/dropload#11]
亲爱的童鞋们，我想请教一下，向下加载数据是写在json里面的，可是为什么一直滑动加载，到大约15次的时候就不加载了呢？这个加载多少怎么控制？如果数据非常多呢？求解

**Comment by ximan** [comment]
可以看我0.5.0的例子，每次取多少数据，你可以自己设置，取完数据，还可以返回无数据提示。
