### ISSUE TITLE
判断上拉和下拉逻辑有些小问题

### ISSUE THREAD

**Issue by Catlite91** [ximan/dropload#13]
发现一个问题，假设从上至下一共有A B C三点，我从B点开始下拉至C，并且能满足出现下拉刷新的updom，此时从C点快速（也许不需要快速）返回到A点，按照逻辑此时获得的手势方向是上拉，resultDom结果是downdom，当然是空，然后执行downdom.css，就回报空指针错误。看一下。
简单的方法是在fnTransition方法执行时判断下dom是否存在。dom && dom.css({...})

**Comment by ximan** [comment]
你好，非常感谢这么仔细的测试。
首先，你一开始说的A B C三点，看你后面的描述，应该是从下至上A B C吧，否则后面的都读不通了。
其次，就算是你这种快速滑动，最后手势方向向上，加载下方的DOM，也不会有影响。因为从0.5.0版本开始，加载下方的DOM不是手势，而是监测scroll滚动条。
而且你这个做法我也没遇到bug，可否麻烦再用最新版试试还有没有这个问题？
非常期待你的答复。

**Comment by Catlite91** [comment]
啊哈，很荣幸收到回复！我按照你说的，用0.6试了下，确实修复了0.4(我用的0.4)中的domresult为空的bug。
        但可能你没理解我的本意，从上至下A B C 三点，理论上用户是从B点往下拉到C点，触发下拉刷新的操作。但当我拉到C点时，仍旧touchmove到A点，此时浏览器的滚动条复原没有我的手势快，当我到达A点时也许才刚刚开始滚动（可以将distance设成更小的值maybe 10 更容易重现）。
        此时touchstart是在B点开始的，touchend是在A点结束的，按照逻辑判断是上滑，me.direction值为up，此时就无法在回调中去除上方的dom节点了。

**Comment by ximan** [comment]
我比较笨哈，按道理来说，我有个参数me.loading，就是为了防止类似情况，网页拉动加载，me.loading=true，加载完毕后，me.loading=false，而且不管是上拉下拉，只有!me.loading才可以执行。
如果新版没这个问题了，我就不继续纠结了
