### ISSUE TITLE
当只使用下拉刷新的时候会报错

### ISSUE THREAD

**Issue by willis325** [ximan/dropload#19]
用户可能会只使用上拉刷新或者只使用下拉加载，这个时候就会报错，需要在代码里面加判断

**Comment by ximan** [comment]
@SoulFlys 不好意思时间有点久不记得你QQ了，麻烦QQ私聊我一下，我看下聊天记录，准备修复此bug。谢谢

**Comment by ximan** [comment]
0.9.0版本已修复，感谢
