### ISSUE TITLE
0.9.0(160215)这个版本好象有BUG

### ISSUE THREAD

**Issue by ahchina** [ximan/dropload#21]
上拉下拉同时加载的案例有这样的问题：先上拉加载完数据显示“暂无数据”后，再下拉刷新，这时下面依然是“暂无数据”，没办法再上拉加载了

**Comment by ximan** [comment]
首先感谢你的反馈，这个不是bug，是我上拉后故意锁住，并且显示暂无数据。而下拉刷新并没有解除这2个，所以就会造成你看到的“bug”。你可以根据你的需求，按需锁定(`lock()`)/解锁(`unlock()`)，暂无数据(`noData()`)/加载数据(`noData(false)`)。
