### ISSUE TITLE
怎么设置上拉才加载？

### ISSUE THREAD

**Issue by jstf9673** [ximan/dropload#22]
请问怎么设置上拉才加载，禁止滑动底部自动加载？

**Comment by joneqing** [comment]
应该可以通过autoload配置项来控制

**Comment by jasonandjay** [comment]
你可以阅读一下源码，你会发现作者设计的时候就是设计成底部监听scroll事件，要想实现上拉加载，也不是太困难，你可以改下源码试一试

**Comment by ximan** [comment]
感谢各位的关注，这个问题我之前标注过，https://github.com/ximan/dropload/blob/gh-pages/Intro.md#050151217
0.5.0(151217)
