### ISSUE TITLE
怎样不一次性加载所有数据

### ISSUE THREAD

**Issue by juzipi** [ximan/dropload#44]
现在是一次性全部加载出来，万一有几万条数据，一开始的加载时间有点长，请问怎么分步骤加载进来。

**Comment by ximan** [comment]
你好，感谢关注此插件。
我在readme里写了一段话：ajax建议自己写，无特殊情况不必copy我的ajax写法。
因为github里没法弄数据库，所以我只能用json模拟，而json又无法分段读取，所以造成现在demo里一次性加载出来。
正规做法应该是请求后台接口，返回指定页数和数量的数据，相信你们后台开发写过分页的都懂。

**Comment by ximan** [comment]
最新版已经加入ajax获取后台分页数据了，欢迎参考。
