### ISSUE TITLE
请问如何较好地重置容器呢？

### ISSUE THREAD

**Issue by kkqy** [ximan/dropload#46]
比方说，我列表上方有个筛选按钮，点击以后，ajax请求会增加一个参数，这个参数会过滤掉一些项.
这样的话，我就需要把列表清空，然后重新加载（我设置了auto自动）。
我目前的做法是单击某个筛选选项以后，触发一个js函数调用，函数里直接把容器内容清空，
然后重新调用dropload(),但总感觉这样做不太完美啊。

**Comment by KuoKongQingYun** [comment]
原来有unlock和resetload 方法……

**Comment by ximan** [comment]
你好，正确的做法应该是me.resetload()重新计算。tab的那个demo里，就是这样处理的，你可以看看。比较麻烦

**Comment by kkqy** [comment]
好的，非常感谢，暂时是解决了。只是一些极端情况还不完美。
比如：如果ajax请求足够慢，同时假设是最后一页数据（或者数据比较少，只有一页），而且在ajax请求完成之前我又点击了tab，这样就会导致一个问题：noData和lock方法调用会晚于我点击tab以后noData(false)和unlock的调用，使得我点击tab以后，在该tab的数据没加载完全的情况下，意外被锁住了。

您的demo是靠tab实现的，几个tab之间的列表互不干涉，这个问题的影响还比较小，我试过在两个tab间快速点击或者连续点击某个tab，偶尔会出现一点小问题，但最终结果是没影响的。而我那个项目由于不太方便使用tab来做，因为分类是动态改变的，所以如使用tab，切换几次以后就会由于页面数据太多而变得非常卡，所以我还是采取的，点击按钮以后，清空列表重新加载的办法，这样的话，我刚刚描述的问题就可能比较明显了。要彻底解决，需要加入额外的同步机制，反正挺麻烦的。

虽然有这个问题，但对于我现在这个项目来说已经足够了，毕竟有的极端情况还是可以忽略的。

**Comment by ximan** [comment]
感谢你的反馈，你提到的这个问题确实会存在，因为我自己tab需求比较少，所以欠缺考虑。
之后有时间更新我会重点考虑这个问题，谢谢。
