### ISSUE TITLE
在require.js同时引入了zepto.js和jquery.js,导致后面出现了有时候无法使用插件

### ISSUE THREAD

**Issue by Georgeliang** [ximan/dropload#56]
由于项目需要用到了require.js，并且同时引用了zepto.js和jquery.js，有时候可以下拉刷新，有时候出现bug:TypeError: $(...).dropload is not a function

**Comment by ximan** [comment]
这个是require的特性，不会按照顺序加载js，有可能页面加载顺序是先执行dropload，后执行jquery，然后就找不到$了。你需要加一句依赖，例如：

```
shim: {  
    'dropload': ['jquery']
},
paths: {
    'jquery': 'xxx',
    'dropload': 'xxx'
}
```

告诉require，dropload必须在jquery执行完后再执行，希望你看得懂

**Comment by Georgeliang** [comment]
这个依赖刚开始就执行了,偶尔出现bug
