### ISSUE TITLE
上拉刷新bug

### ISSUE THREAD

**Issue by huhuamin** [ximan/dropload#60]
http://ximan.github.io/dropload/examples/load-top-bottom.html#3
![2016-11-10 18 10 33](https://cloud.githubusercontent.com/assets/14198206/20172682/068f7922-a771-11e6-98b2-74626929caa4.png)
当火狐浏览器缩放到30%，360×640宽度，上啦刷新之后不能加载更多。
在生产环境用遇到这样的问题，一页加载10条，但是没有把页面铺满，就不会加载更多。
但是刷新url地址会自动加载更多.
上面的官网的url demo也有这样的问题

**Comment by ximan** [comment]
感谢反馈，此bug在0.9.1版本已经修复，欢迎测试。
