### ISSUE TITLE
浏览器改变大小导致刷新失败

### ISSUE THREAD

**Issue by liangyangtao** [ximan/dropload#61]
操作步骤
打开谷歌或火狐浏览器（此时是全屏的）
输入第一个测试用例
http://ximan.github.io/dropload/examples/load-bottom.html 
发现下拉加载，下拉数据会继续刷新出来

重新打开一个窗口（此时是全屏的）
输入测试用例
http://ximan.github.io/dropload/examples/load-bottom.html 
此时把浏览器拉小，下拉加载数据失效 效果如下（如果加载完的话是显示暂无数据）

![qq 20161201155019](https://cloud.githubusercontent.com/assets/5389893/20785946/fd6ce654-b7dd-11e6-92ba-c2f1828dd422.jpg)

**Comment by ximan** [comment]
感谢反馈，此bug在0.9.1版本已经修复，欢迎测试。
