### ISSUE TITLE
拖动的时候会导致列表抖动

### ISSUE THREAD

**Issue by exdestroyer** [ximan/dropload#7]
![qq 20151019144514](https://cloud.githubusercontent.com/assets/6057034/10571337/dc8c1e96-7670-11e5-8d17-5b64c208b7ef.png)
我发现上拉的时候会导致列表上下抖动，好像是因为
touchmove的时候这句
me._curY = e.touches[0].pageY;
因为每次拉的时候位置会因为页面上移而跟着变动导致数值一上一下的，这个bug有办法解决吗

**Comment by linkkingjay** [comment]
+1

先往上拉一点点再往下拉就会抖动很厉害，iPhone 6：Safari 和微信中都有这个情况。

**Comment by gu-xionghong** [comment]
求解决方案

**Comment by mercer08** [comment]
同遇到问题,还有在更新吗?

**Comment by ximan** [comment]
非常感谢各位使用和反馈，这个问题貌似和浏览器自身的设计有关，我还不太确定如何解决。近期或许会把这个上拉的换成scroll判断算了，或许体验会更好。
同时也欢迎各位提供解决方案，pull requests

**Comment by devinRex** [comment]
建议使用translate3D，不要去通过height改变

**Comment by ximan** [comment]
@devinRex 感谢关注。
我是通过增加下方loading容器的height，来让整个列表往上移动的。如果用translate3D让列表上移，加载出来的内容跟原有的内容就不连贯了吧。

**Comment by devinRex** [comment]
@ximan 多谢回复。
你提到的这点我倒是没有考虑到。下拉其实也会有这个问题，因为也是改变loading容器的height，这个通过translate3D修改是没问题的。上拉这个我有时间会试着去改一下，看有没有办法解决这个不连贯的问题。

**Comment by ximan** [comment]
@devinRex 下拉貌似没有人反馈说有卡顿吧，虽然没用硬件加速，但在scrollTop为0的时候，增加上方的height，卡顿现象还好。主要是下方，高度增加会跟浏览器的滚动条产生影响，目前我是这样认为的。

**Comment by zhangkuiworld** [comment]
同样的问题，@ximan 有解决方案么

**Comment by ximan** [comment]
已经更新0.5.0，上拉改为了scroll，所以不会再卡顿了
