### ISSUE TITLE
快速滑动时，会出现报错

### ISSUE THREAD

**Issue by willwong123** [ximan/dropload#8]
快速页面上滑动的时候，会出现js报错，导致接下来再刷新就无法操作。

报错如下：

> dropload.js:214   Uncaught TypeError: Cannot read property 'on' of undefined

环境： 
- chrome 46 
- dropload 4.0

**Comment by ximan** [comment]
感谢反馈，有空我重现试试

**Comment by ximan** [comment]
已经更新0.5.0，麻烦再试试还有没有报错，谢谢
